from enum import Enum, auto

class TipoNodo(Enum):
	PROGRAMA = auto()
	ASIGNACIÓN = auto()
	EXPRESIÓN_MATEMÁTICA = auto()
	EXPRESIÓN = auto()
	FUNCIÓN = auto()
	INVOCACIÓN = auto()
	PARÁMETROS = auto()
	PARÁMETROS_INVOCACIÓN = auto()
	INSTRUCCIÓN = auto()
	REPETICIÓN = auto()
	BIFURCACIÓN = auto()
	ANTIANARQUÍA = auto()
	OPERADOR_LÓGICO = auto()
	CONDICIÓN = auto()
	COMPARACIÓN = auto()
	RETORNO = auto()
	ERROR = auto()
	PRINCIPAL = auto()
	BLOQUE_INSTRUCCIONES = auto()
	OPERADOR = auto()
	VALOR_LOGICO = auto()
	COMPARADOR = auto()
	TEXTO = auto()
	ENTERO = auto()
	FLOTANTE = auto()
	IDENTIFICADOR = auto()
	VALOR = auto()
	ERROR_FALTA_INICIALIZADOR = auto()

